name: Push Docker Image to Docker Hub # Workflow name

on: # Triggering conditions
  push: # Trigger when branches or tags are pushed
    branches:
      - 'main' # Only on the master branch
    tags:
      - '**' # Trigger for all tags

jobs: # Job definitions
  push: # Job name
    runs-on: ubuntu-latest # Use the latest Ubuntu machine

    steps:
      - name: Checkout # Download repository code to the runner
        uses: actions/checkout@v2 # Checkout specific branch

      - name: Docker meta # Step name is user-defined
        id: docker_meta # ID for reusing outputs in other steps
        uses: crazy-max/ghaction-docker-meta@v1 # Using docker-meta action
        with: # Declare input values for the action
          images: d7mekz/nodejs-ci # Docker repository (account/repo)
          tag-semver: | # Tags to use for versioning
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU # QEMU is an open-source hypervisor
        uses: docker/setup-qemu-action@v2 # Emulator to run apps on other platforms

      - name: Set up Docker Buildx # Buildx feature included in Docker 19.03+
        uses: docker/setup-buildx-action@v2 # Build for other platforms

      - name: Login to Docker Hub # Docker Hub login action
        uses: docker/login-action@v2 # Docker login action
        with: # Declare input values for the action
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Docker Hub username secret
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} # Docker Hub password secret

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true # Confirm image push after build
          tags: ${{ steps.docker_meta.outputs.tags }} # Use tags defined in the Docker meta step
          labels: ${{ steps.docker_meta.outputs.labels }} # Use labels defined in the Docker meta step
